// <auto-generated />
using System;
using EcoTag.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoTag.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoTag.Models.FatorEmissaoModel", b =>
                {
                    b.Property<string>("TipoCombustivel")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double>("ConsumoAdicionalAceleracao")
                        .HasColumnType("double precision");

                    b.Property<double>("ConsumoMarchaLenta")
                        .HasColumnType("double precision");

                    b.Property<double>("FatorEmissao")
                        .HasColumnType("double precision");

                    b.HasKey("TipoCombustivel");

                    b.ToTable("FatoresEmissao");

                    b.HasData(
                        new { TipoCombustivel = "gasolina", FatorEmissao = 2.31, ConsumoMarchaLenta = 0.8, ConsumoAdicionalAceleracao = 0.015 },
                        new { TipoCombustivel = "etanol", FatorEmissao = 1.53, ConsumoMarchaLenta = 1.0, ConsumoAdicionalAceleracao = 0.018 },
                        new { TipoCombustivel = "diesel", FatorEmissao = 2.68, ConsumoMarchaLenta = 1.2, ConsumoAdicionalAceleracao = 0.02 });
                });

            modelBuilder.Entity("EcoTag.Models.ParametrosCenarioSemTagModel", b =>
                {
                    b.Property<string>("TipoLocal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double>("EmissaoTicketPapelKg")
                        .HasColumnType("double precision");

                    b.Property<int>("TempoEsperaCabineSegundos")
                        .HasColumnType("integer");

                    b.Property<int>("TempoMedioFilaMinutos")
                        .HasColumnType("integer");

                    b.HasKey("TipoLocal");

                    b.ToTable("ParametrosCenarioSemTag");

                    b.HasData(
                        new { TipoLocal = "pedagio", TempoMedioFilaMinutos = 3, TempoEsperaCabineSegundos = 20, EmissaoTicketPapelKg = 0.002 },
                        new { TipoLocal = "estacionamento", TempoMedioFilaMinutos = 2, TempoEsperaCabineSegundos = 15, EmissaoTicketPapelKg = 0.001 });
                });

            modelBuilder.Entity("EcoTag.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcoTag.Models.LocalUsoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoLocal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("TipoLocal");

                    b.ToTable("LocaisUso");

                    b.HasData(
                        new { Id = 1, Nome = "Pedagio Demo", TipoLocal = "pedagio" },
                        new { Id = 2, Nome = "Estacionamento Demo", TipoLocal = "estacionamento" });
                });

            modelBuilder.Entity("EcoTag.Models.VeiculoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoCombustivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TipoVeiculo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoCombustivel");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("EcoTag.Models.PassagemTagModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Co2EvitadoKg")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LocalUsoId")
                        .HasColumnType("integer");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalUsoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("PassagensTag");
                });

            modelBuilder.Entity("EcoTag.Models.LocalUsoModel", b =>
                {
                    b.HasOne("EcoTag.Models.ParametrosCenarioSemTagModel", "ParametrosCenario")
                        .WithMany("LocaisUso")
                        .HasForeignKey("TipoLocal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParametrosCenario");
                });

            modelBuilder.Entity("EcoTag.Models.VeiculoModel", b =>
                {
                    b.HasOne("EcoTag.Models.FatorEmissaoModel", "FatorEmissao")
                        .WithMany("Veiculos")
                        .HasForeignKey("TipoCombustivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoTag.Models.UserModel", "Usuario")
                        .WithMany("Veiculos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FatorEmissao");
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoTag.Models.PassagemTagModel", b =>
                {
                    b.HasOne("EcoTag.Models.LocalUsoModel", "LocalUso")
                        .WithMany("Passagens")
                        .HasForeignKey("LocalUsoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoTag.Models.VeiculoModel", "Veiculo")
                        .WithMany("Passagens")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalUso");
                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("EcoTag.Models.FatorEmissaoModel", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("EcoTag.Models.LocalUsoModel", b =>
                {
                    b.Navigation("Passagens");
                });

            modelBuilder.Entity("EcoTag.Models.ParametrosCenarioSemTagModel", b =>
                {
                    b.Navigation("LocaisUso");
                });

            modelBuilder.Entity("EcoTag.Models.UserModel", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("EcoTag.Models.VeiculoModel", b =>
                {
                    b.Navigation("Passagens");
                });
#pragma warning restore 612, 618
        }
    }
}
