BEGIN;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" varchar(150) NOT NULL,
    "ProductVersion" varchar(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS "FatoresEmissao" (
    "TipoCombustivel" varchar(30) NOT NULL,
    "FatorEmissao" double precision NOT NULL,
    "ConsumoMarchaLenta" double precision NOT NULL,
    "ConsumoAdicionalAceleracao" double precision NOT NULL,
    CONSTRAINT "PK_FatoresEmissao" PRIMARY KEY ("TipoCombustivel")
);

CREATE TABLE IF NOT EXISTS "ParametrosCenarioSemTag" (
    "TipoLocal" varchar(30) NOT NULL,
    "TempoMedioFilaMinutos" integer NOT NULL,
    "TempoEsperaCabineSegundos" integer NOT NULL,
    "EmissaoTicketPapelKg" double precision NOT NULL,
    CONSTRAINT "PK_ParametrosCenarioSemTag" PRIMARY KEY ("TipoLocal")
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" varchar(100) NOT NULL,
    "Email" varchar(150) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" varchar(30) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "LocaisUso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" varchar(100) NOT NULL,
    "TipoLocal" varchar(30) NOT NULL,
    CONSTRAINT "PK_LocaisUso" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LocaisUso_ParametrosCenarioSemTag_TipoLocal"
        FOREIGN KEY ("TipoLocal")
        REFERENCES "ParametrosCenarioSemTag" ("TipoLocal")
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Veiculos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "TipoVeiculo" varchar(30) NOT NULL,
    "TipoCombustivel" varchar(30) NOT NULL,
    CONSTRAINT "PK_Veiculos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Veiculos_FatoresEmissao_TipoCombustivel"
        FOREIGN KEY ("TipoCombustivel")
        REFERENCES "FatoresEmissao" ("TipoCombustivel")
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Veiculos_Users_UsuarioId"
        FOREIGN KEY ("UsuarioId")
        REFERENCES "Users" ("Id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "PassagensTag" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VeiculoId" integer NOT NULL,
    "LocalUsoId" integer NOT NULL,
    "DataHora" timestamp with time zone NOT NULL,
    "Co2EvitadoKg" double precision NOT NULL,
    CONSTRAINT "PK_PassagensTag" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PassagensTag_LocaisUso_LocalUsoId"
        FOREIGN KEY ("LocalUsoId")
        REFERENCES "LocaisUso" ("Id")
        ON DELETE RESTRICT,
    CONSTRAINT "FK_PassagensTag_Veiculos_VeiculoId"
        FOREIGN KEY ("VeiculoId")
        REFERENCES "Veiculos" ("Id")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
CREATE INDEX IF NOT EXISTS "IX_LocaisUso_TipoLocal" ON "LocaisUso" ("TipoLocal");
CREATE INDEX IF NOT EXISTS "IX_Veiculos_TipoCombustivel" ON "Veiculos" ("TipoCombustivel");
CREATE INDEX IF NOT EXISTS "IX_Veiculos_UsuarioId" ON "Veiculos" ("UsuarioId");
CREATE INDEX IF NOT EXISTS "IX_PassagensTag_LocalUsoId" ON "PassagensTag" ("LocalUsoId");
CREATE INDEX IF NOT EXISTS "IX_PassagensTag_VeiculoId" ON "PassagensTag" ("VeiculoId");

INSERT INTO "FatoresEmissao"
    ("TipoCombustivel", "ConsumoAdicionalAceleracao", "ConsumoMarchaLenta", "FatorEmissao")
VALUES
    ('diesel', 0.02, 1.2, 2.68),
    ('etanol', 0.018, 1.0, 1.53),
    ('gasolina', 0.015, 0.8, 2.31)
ON CONFLICT ("TipoCombustivel") DO NOTHING;

INSERT INTO "ParametrosCenarioSemTag"
    ("TipoLocal", "EmissaoTicketPapelKg", "TempoEsperaCabineSegundos", "TempoMedioFilaMinutos")
VALUES
    ('estacionamento', 0.001, 15, 2),
    ('pedagio', 0.002, 20, 3)
ON CONFLICT ("TipoLocal") DO NOTHING;

INSERT INTO "LocaisUso"
    ("Id", "Nome", "TipoLocal")
VALUES
    (1, 'Pedagio Demo', 'pedagio'),
    (2, 'Estacionamento Demo', 'estacionamento')
ON CONFLICT ("Id") DO NOTHING;

SELECT setval(pg_get_serial_sequence('"LocaisUso"', 'Id'), GREATEST((SELECT COALESCE(MAX("Id"), 1) FROM "LocaisUso"), 1));

INSERT INTO "__EFMigrationsHistory"
    ("MigrationId", "ProductVersion")
VALUES
    ('20260529190000_InitialEcoTag', '10.0.3')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
